### PR TITLE
Fix compiler warnings with Elixir 1.17

### PR DESCRIPTION
**Pull request by Moosieus**
* Use `~c''` instead of `''`
* Use `import Config` instead of `import Mix.Config`
* Use latest version of ex_doc
* Set minimum Elixir version to `1.13` per ex_doc requirements

### CODE REVIEW

**Comment by Moosieus** [comment]
Also incrementing Patch from `0.13.1` to `0.14.0` due to incrementing the minimum version requirement.

**Comment by ihumanable** [comment]
I'm not really sure why support for Elixir 1.7-1.13 is removed in this PR.  Someone consuming the library isn't going to be trying to generate documentation for the library, while the library development must happen on 1.13+ to use ex_doc, the users of patch aren't required to be bound by that.

**Comment by Moosieus** [comment]
In that case, would the minimum supported version would be `1.9`?

Per the switch from `Mix.Config` to `Config`.

**Comment by ihumanable** [comment]
That seems acceptable to me, if people would like to use patch on 1.7 or 1.8 I suppose they can stay on an older version and we can remove them from the support matrix.  

If you update the elixir version to 1.9 then this can merge.  Thank you for making Patch better.

**Pull request merged**
